; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitc-02]
platform = espressif32
board = esp32-c3-devkitc-02
framework = espidf
build_flags =
    -I./include
test_ignore = test_desktop

[env:native]
platform = native
# Tell PlatformIO to only run tests in the test_desktop folder for the PC
test_filter = test_logic
build_flags =
    -I./include

